name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip custom component
        run: |
          cd custom_components/pgw
          zip -r pgw.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/pgw/pgw.zip
